# Generated by Django 4.2.6 on 2023-11-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_other_user_data_otheruserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheruserdata',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
