# Generated by Django 4.2.6 on 2023-11-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_suscriptors_lastname_remove_suscriptors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='token',
        ),
    ]
