# Generated by Django 4.2.6 on 2023-11-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_doctors_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptors',
        ),
    ]
