# Generated by Django 4.2.6 on 2023-11-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_suscriptors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
